name: 'broken-link-check'
description: 'Find broken links, missing images, etc within your HTML.'
author: 'Celine Kurpershoek'
inputs:
  url:  # id of input
    description: 'Url of site'
    required: true
    default: 'https://google.com'
  env:
    CONFIG_FILE: 'Path to config file'
    required: false
    default: ''
outputs:
  result: # id of output
    description: 'Report of links'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.url }}